kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-dev
rules:
  # pod get/watch is used to identify the container IDs of the current pod
  - apiGroups:
      - ""
    resources:
      - pods
      - volumes
      - persistentvolumes
      - pods/log
      - pods/exec
      - configmaps
    verbs:
      - get
      - create
      - watch
      - patch
      - list
      - delete
      - update
  - apiGroups: ["argoproj.io"] 
    resources:
      - workflows
    verbs:
      - get
      - create
      - watch
      - patch
      - list
      - delete
  - apiGroups: ["workflows.argoproj.io"] 
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - delete