[rq2.pyright]
include = ["."]
exclude = ["__pycache__"]
defineConstant = { DEBUG = true }
venv = "rq2_venv"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.9"

#executionEnvironments = [
#  { root = "src/web", pythonVersion = "3.5", pythonPlatform = "Windows", extraPaths = [ "src/service_libs" ] },
#  { root = "src/sdk", pythonVersion = "3.0", extraPaths = [ "src/backend" ] },
#  { root = "src/tests", extraPaths = ["src/tests/e2e", "src/sdk" ]},
#  { root = "src" }
#]
