name: analyzer
version: "1.0"
author: Javier Cabrera <javierca@kth.se>
about: Process Wasm binaries. This is a compound of slumps tools, all migrated to a Rust implementation
subcommands:
    - extract:
        about: Extract metadata information from the binaries
        args:
        - folder:
            required: true
            help: "Folder containing the binaries"
            value_name: "folder"
        - reset:
            short: r
            help: "Clean out database before starting the extraction of metadatas"
        - depth:
            short: d
            required: false
            takes_value: true
            value_name: "depth"
            long: depth
            help: "How deep the extraction should go (0 for the minimum)"

    - export:
        about: Export database data as a JSON file
        args:
          - out:
              takes_value: true
              help: Output file
          - list:
                short: l
                help: "List collections"
            
    - reduce:
        about: Takes a folder of Wasm binaries and apply the reduction implementation of wasm-mutate. It saves the new binary in the out directory and creates an entry in the db with the canonical representation of the original binary
        args:
            - folder:
                required: true
                help: "Folder containing the binaries"
                value_name: "folder"
                takes_value: true
                short: f
                long: folder
            - out:
                required: true
                help: "Folder containing the canonical representation"
                takes_value: true
                value_name: "out"
                short: o
                long: out
            - reset:
                short: r
                help: "Clean out database before starting the extraction of metadatas"
            - save_logs:
                required: false
                short: s
                long: save-logs
                help: "Save reduction logs from wasm-shrink"
    - clean:
        about: Hard reset the database
    
    - reduce:
        about: Reduce binary to its minimal expression according to wasm-mutate implementation

    - diversify:
        about: Diversify source code, input C/C++, Wasm or LLVM
        args:
          - out:
              help: Out file, type of output is decided by file extension
args:
  - dbpass:
      required: true
      help: "Mongo db pass" 
      value_name: "pass"
      takes_value: true
  - dbuser:
      required: true 
      value_name: "user"
      help: "Mongo db username"
      takes_value: true
  - dbconn:
      default_value: "mongodb://localhost:27017"
      help: "Mongo db connection string"
      value_name: "dbconn"
      takes_value: true
  - dbname:
      default_value: "obfuscator"
      required: false
      takes_value: true
      value_name: dbname
      
  - collection_name:
      default_value: "wasms"
      required: false
      takes_value: true
      value_name: collection_name
      long: collection_name
      short: t
    