name: Build and deploy release
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main
    paths:
      - crates/**
      - oracles/**
      - .github/**

jobs:
  build:
    name: Build binaries
    # This job runs on Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl --proto '=https' -y --tlsv1.2 -sSf https://sh.rustup.rs | sh 

      - name: Set nightly
        run: |
          rustup default nightly

      - name: Build binaries
        run: |
          cd crates/evasor
          cargo build --release

      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: crates/evasor/target/release/evasor
          asset_name: evasor_linux_amd64
          tag: 0.1.0
          overwrite: true
          body: "Evasor binary for linux"

